### ISSUE TITLE
Paginator: Exception after the end of a timeout

### ISSUE THREAD

**Issue by Distractic** [Kotlin-Discord/kord-extensions#15]
# Paginator: Exception with the timeout 

## Problem

When you create a _Paginator_ with a _timeout_ value and several pages (in order to get the deletion reaction). 

```kotlin
Paginator(bot, timeout = 5000 , pages = pages, targetMessage = message, owner = message.author!!)
```

When a user deletes the Paginator with the delete reaction and after this event the end of the timeout is activated, it creates an exception in the console.

### Paginator in Discord

![image](https://user-images.githubusercontent.com/46402441/103782929-63577a00-5038-11eb-9740-c63328721c49.png)

### Exception in console

```
ERROR com.kotlindiscord.kord.extensions.commands.Command - Error during execution of ping command (MessageCreateEvent ..)
dev.kord.rest.request.KtorRequestException: REST request returned with HTTP 404 Not Found. UnknownMessage: Unknown Message
	at dev.kord.rest.request.KtorRequestHandler.handle(KtorRequestHandler.kt:61)
	at dev.kord.rest.request.KtorRequestHandler$handle$1.invokeSuspend(KtorRequestHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gdude2002** [comment]
Fixed in https://github.com/Kord-Extensions/kord-extensions/commit/e352598a1a7e1354eb3a775c1e61b66cc5c0410e
