### ISSUE TITLE
UninitializedPropertyAccessException when using group function of Paginator

### ISSUE THREAD

**Issue by doublemoon1119** [Kotlin-Discord/kord-extensions#165]
# Description

- I'm using group function of Paginator.

Exception log:
```
2022-07-08 10:18:31.871 [DefaultDispatcher-worker-8] ERROR c.k.k.e.c.a.slash.SlashCommand - Error during execution of help slash command (dev.kord.core.event.interaction.GuildChatInputCommandInteractionCreateEvent@3b4eecef)
kotlin.UninitializedPropertyAccessException: lateinit property text has not been initialized
	at dev.kord.rest.builder.message.EmbedBuilder$Footer.getText(EmbedBuilder.kt:180)
	at com.kotlindiscord.kord.extensions.pagination.pages.Page$build$2.invokeSuspend(Page.kt:63)
	at com.kotlindiscord.kord.extensions.pagination.pages.Page$build$2.invoke(Page.kt)
	at com.kotlindiscord.kord.extensions.pagination.pages.Page$build$2.invoke(Page.kt)
	at com.kotlindiscord.kord.extensions.pagination.BasePaginator.applyPage$suspendImpl(BasePaginator.kt:109)
	at com.kotlindiscord.kord.extensions.pagination.BasePaginator.applyPage(BasePaginator.kt)
	at com.kotlindiscord.kord.extensions.pagination.PublicResponsePaginator.send(PublicResponsePaginator.kt:47)
	at me.doublemoon.kordex.extensions.HelpExtension$setup$2$1.invokeSuspend(HelpExtension.kt:48)
	at me.doublemoon.kordex.extensions.HelpExtension$setup$2$1.invoke(HelpExtension.kt)
	at me.doublemoon.kordex.extensions.HelpExtension$setup$2$1.invoke(HelpExtension.kt)
	at com.kotlindiscord.kord.extensions.commands.application.slash.PublicSlashCommand.run(PublicSlashCommand.kt:107)
	at com.kotlindiscord.kord.extensions.commands.application.slash.PublicSlashCommand$run$1.invokeSuspend(PublicSlashCommand.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

# Versions

- KordEx: 1.5.4-SNAPSHOT

# Suggestions

I think that's the problem

https://github.com/Kord-Extensions/kord-extensions/blob/254cc238264bd4c257b433d5648c0fba32a3e09a/kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/pagination/pages/Page.kt#L63

https://github.com/Kord-Extensions/kord-extensions/blob/254cc238264bd4c257b433d5648c0fba32a3e09a/kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/pagination/pages/Page.kt#L85

```text.isNotBlank()``` should be changed to ```this.isNotBlank()```

**Comment by gdude2002** [comment]
You are correct - I've just pushed a fix for this, and it'll be available in the latest snapshot shortly. Thanks!
