### ISSUE TITLE
EmojiConverter will crash with a normal emoji

### ISSUE THREAD

**Issue by Doomsdayrs** [Kotlin-Discord/kord-extensions#176]
# Description

[Line 79](https://github.com/Kord-Extensions/kord-extensions/blob/298eeadb3a1bba500b7e70714365b4715fcf36f6/kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/commands/converters/impl/EmojiConverter.kt#L79) of EmojiConverter causes a crash.

**Comment by gdude2002** [comment]
This issue doesn't have close to enough information. What version of KordEx are you using? What exception is being thrown? Can you provide logs or more context?

**Comment by Doomsdayrs** [comment]
> This issue doesn't have close to enough information. What version of KordEx are you using? What exception is being thrown? Can you provide logs or more context?

I just use `+`, so latest. Asides the link is right from the latest git.

NoSuchElementException

```
Exception in thread "DefaultDispatcher-worker-6" java.util.NoSuchElementException: Expected at least one element matching the predicate (dev.kord.core.entity.GuildEmoji) -> kotlin.Boolean
	at kotlinx.coroutines.flow.FlowKt__ReduceKt.first(Reduce.kt:114)
	at kotlinx.coroutines.flow.FlowKt.first(Unknown Source)
	at com.kotlindiscord.kord.extensions.commands.converters.impl.EmojiConverter$findEmoji$$inlined$mapNotNull$3$2.emit(Emitters.kt:224)
	at kotlinx.coroutines.flow.FlowKt__EmittersKt$onEmpty$1$1.emit(Emitters.kt:185)
	at dev.kord.core.supplier.CacheEntitySupplier$special$$inlined$map$2$2.emit(Emitters.kt:224)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66)
	at dev.kord.cache.map.MapLikeCollection$Companion$from$1$values$1.invokeSuspend(MapLikeCollection.kt:89)
	at dev.kord.cache.map.MapLikeCollection$Companion$from$1$values$1.invoke(MapLikeCollection.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at dev.kord.core.supplier.CacheEntitySupplier$special$$inlined$map$2.collect(SafeCollector.common.kt:113)
	at kotlinx.coroutines.flow.FlowKt__EmittersKt$onEmpty$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:114)
	at com.kotlindiscord.kord.extensions.commands.converters.impl.EmojiConverter$findEmoji$$inlined$mapNotNull$3.collect(SafeCollector.common.kt:113)
	at kotlinx.coroutines.flow.FlowKt__ReduceKt.firstOrNull(Reduce.kt:228)
	at kotlinx.coroutines.flow.FlowKt.firstOrNull(Unknown Source)
	at com.kotlindiscord.kord.extensions.commands.converters.impl.EmojiConverter.findEmoji(EmojiConverter.kt:89)
	at com.kotlindiscord.kord.extensions.commands.converters.impl.EmojiConverter.parseOption(EmojiConverter.kt:99)
	at com.kotlindiscord.kord.extensions.commands.application.slash.SlashCommandParser.parse(SlashCommandParser.kt:82)
	at com.kotlindiscord.kord.extensions.commands.application.slash.PublicSlashCommand.run(PublicSlashCommand.kt:96)
	at com.kotlindiscord.kord.extensions.commands.application.slash.PublicSlashCommand$run$1.invokeSuspend(PublicSlashCommand.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@797bf9b1, Dispatchers.Default]
```

**Comment by gdude2002** [comment]
Thanks for the PR!
