### ISSUE TITLE
Data collection warning when plugins disabled

### ISSUE THREAD

**Issue by zt64** [Kotlin-Discord/kord-extensions#324]
# Description

When the data collection process is running and it comes to the plugins manager an error occurs if the manager variable isn't initialized. This can happen when the plugins feature is disabled through `pluginBuilder.enabled = false`

```
kotlin.UninitializedPropertyAccessException: lateinit property managerObj has not been initialized
	at dev.kordex.core.builders.ExtensibleBotBuilder$PluginBuilder.getManagerObj$kord_extensions(ExtensibleBotBuilder.kt:769)
	at dev.kordex.core.datacollection.DataCollector.collect$kord_extensions(DataCollector.kt:139)
	at dev.kordex.core.datacollection.DataCollector$collect$1.invokeSuspend(DataCollector.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
```

# Versions

* KordEx: 2.1.0-SNAPSHOT

**Comment by gdude2002** [comment]
Thanks, good catch!

I'll fix that now, I was planning to get a new release out tonight anyway.
